---
- name: Install Required Packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - centos-release-scl
   - mariadb-server
   - mariadb
   
- name: Updating root password
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    
- name: Removing anonymous MySQL user
  mysql_user: name="" host={{item}} state=absent
  with_items:
    - localhost

- name: Removing test database
  mysql_db: name=test state=absent
  
- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  
- name: Set root user password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true

- name: Create .my.cnf for credentials
  template:
   src: "my.cnf"
   dest: "/root/.my.cnf"
   mode: 0600
 
- mysql_user:
    name: wiki
    password: "{{ mysql_wikiuser_password }}"
    priv: '*.*:ALL'
    state: present

- name: Give database privileges
  community.mysql.mysql_user:
    name: wiki
    password: {{ mysql_wikiuser_password }}"
    priv: 'wikidatabase.*'
    state: present